COD-61: API для форума
kakbutos/MatchThree pull request #27
Opened 2024-02-04 15:13 UTC by kakbutos

### Какую задачу решаем
Реализовать API для форума: https://linear.app/codefather/issue/COD-61/realizovat-api-dlya-foruma

### Скриншоты/видяшка (если есть)

### TBD (если есть)

Прикрутил orm - sequelize и накинул пример как создать модель
Сейчас можно запустить с корня проекта контейнер через `docker compose up` - это поднимет вам бдшку postgres
А в соседнем терминале запустить сервак уже и работать

2024-02-06 20:17 UTC, kakbutos commented on docker-compose.yml
> +#          SERVER_PORT: ${SERVER_PORT}
Закомментил пока что, потому что это отдельное задание перенести сборку в докер

2024-02-06 20:27 UTC, shumilina-polina approved these changes

2024-02-07 07:37 UTC, Olegas commented on packages/server/controllers/TopicController.ts
> +          [Op.iLike]: `%${searchTitle}%`,
Если есть операция поиска по тексту, на это поле должен быть индекс соответствующего типа. Почитай например вот этот вопрос на SO https://dba.stackexchange.com/questions/4521/how-to-create-an-index-to-speed-up-an-aggregate-like-query-on-an-expression

2024-02-07 07:40 UTC, Olegas requested changes
Добрый день. Есть замечания к коду. Нужно доработать. Написал комментарии.

2024-02-07 07:40 UTC, Olegas commented on packages/server/controllers/ReplyController.ts
> +          commentId: comment.id,
На поле commentId должен быть индекс для того что бы такой поиск работал быстро. А вообще это лучше делать за один запрос а не за несколько. Можно попросить базу выбрать все комментарии с данными идентификаторами

2024-02-07 07:40 UTC, Olegas commented on packages/server/controllers/CommentController.ts
> +        topicId: +topicId,
Должен быть индекс по topicId что бы этот запрос работал эффективно

2024-02-07 07:40 UTC, Olegas commented on packages/server/controllers/ReplyController.ts
> +      userId: number;
Есть ли у вас в проекте мидлвара, которая проверяет авторизацию на серверной стороне? Если есть, то идентификатор пользователя надо брать из нее, а не доверять клиенту. Если пока нет - можно оставить так, но когда появится лучше переделать

2024-02-07 09:11 UTC, kakbutos commented on packages/server/controllers/TopicController.ts
> +          [Op.iLike]: `%${searchTitle}%`,
Добавил индекс

2024-02-07 09:12 UTC, kakbutos commented on packages/server/controllers/ReplyController.ts
> +          commentId: comment.id,
Сделал в один запрос

2024-02-07 09:12 UTC, kakbutos commented on packages/server/controllers/CommentController.ts
> +        topicId: +topicId,
Добавил индекс

2024-02-07 09:17 UTC, kakbutos commented on packages/server/controllers/ReplyController.ts
> +      userId: number;
Я везде добавил `userId`, с той логикой, что у топика, комментария и ответа везде есть аватарки пользователя и тп, чтоб можно было понимать кто оставил этот коммент или создал топик.

Насчет мидлвары авторизации, ее пока нет, но у меня вопрос по ней. Насколько я понимаю сейчас есть какие-то ограничения на сервере, что нельзя стучаться за инфой о пользователи к яндексу? (было сказано в вебинарах и пока не занимались этим). Там сказали будет в каком-то спринте показан обход этого, это так?

2024-02-08 12:27 UTC, Olegas commented on packages/server/models/Topic.ts
> +      fields: ['title'],
Для поиска по частичному совпадению обычного индекса недостаточно. Посмотри еще раз ссылку, которую я раньше скидывал - там речь о том, что создается индекс специального типа

2024-02-08 12:28 UTC, Olegas approved these changes
Работу принимаю. Но обрати пожалуйста внимание на создание индекса для поиска по частичному вхождению текста. Что бы это работало, нужно создавать индекс определенного типа

2024-02-09 11:55 UTC, kakbutos commented on packages/server/models/Topic.ts
> +      fields: ['title'],
хорошо, в отдельном мерже добавлю индекс специального типа

2024-02-09 11:55 UTC, merged