Поддержка API форума на клиенте
kakbutos/MatchThree pull request #28
Opened 2024-02-09 13:50 UTC by shumilina-polina

- получение/создание топиков, комментариев и ответов на комментарии
- поиск по названию темы

<img width="1440" alt="Снимок экрана 2024-02-09 в 16 43 04" src="https://github.com/kakbutos/MatchThree/assets/63950558/22dfa41a-55e8-4cef-ad36-e97e6338874c">

<img width="1440" alt="image" src="https://github.com/kakbutos/MatchThree/assets/63950558/5805fa66-ebb0-434d-9bba-f91c4d58cbae">

2024-02-09 15:13 UTC, kakbutos commented on packages/client/src/widgets/profile-form/ProfileForm.tsx
> +export const sanitizeObject = (obj: object) =>
вынеси в utils, раз еще где-то исопользуешь

2024-02-09 15:14 UTC, kakbutos commented on packages/client/src/widgets/create-theme-dialog/CreateThemeDialog.tsx
> +      console.log(error);
если есть желание, можно как в профиле добавить типс об ошибке, чтоб было отзывчиво

2024-02-09 15:15 UTC, kakbutos approved these changes
кайф

2024-02-09 15:49 UTC, belyshevaoksanai approved these changes

2024-02-10 11:16 UTC, shumilina-polina commented on packages/client/src/widgets/profile-form/ProfileForm.tsx
> +export const sanitizeObject = (obj: object) =>
не использую в итоге, забыла убрать export

2024-02-10 15:33 UTC, Olegas commented on packages/client/src/pages/topic/Topic.tsx
> +      const comments = await getComments({ topicId: id as string });
Совет: лучше делать так, что бы не надо было несколько раз ходить на сервер если можно за раз. Тут комментарии вполне можно сразу загрузить на бэке вместе с топиком и там же отсортировать

2024-02-10 15:35 UTC, Olegas commented on packages/client/src/widgets/comment-form/CommentForm.tsx
> +        userId: authUser.id as string,
Не забыть: когда появится мидлвара, которая будет проверять авторизацию, здесь надо убрать явную передачу ид автора, вместо этого вычислять его на сервере

2024-02-10 15:38 UTC, Olegas commented on packages/client/src/widgets/comment/Reply.tsx
> +              style={{ width: '25px', height: '25px' }}
Совет: такие стили лучше выносить за рамки компоненте или делать через CSS. Иначе каждый рендер текущего компонента Avatar получает новые пропсы и перестраивается

2024-02-10 15:41 UTC, Olegas commented on packages/client/src/widgets/comment/Comment.tsx
> +      {comment.replies?.sort(sortByDate).map(reply => (
Совет: сортировки лучше мемоизировать а не делать каждый рендер заново

2024-02-10 15:43 UTC, Olegas commented on packages/client/src/widgets/comment/Reply.tsx
> +    getUserById();
Нет, так нельзя. Это надо переделать. У вас в комментарии выводятся ответы. И для каждого ответа делается запрос на сервер за данными об авторе. Надо либо присылать эти данные сразу с сервера или делать какой-то массовый запрос, или хотя бы не ходить несколько раз за одним и тем же пользователем. Ведь сейчас если от одного автора будет несколько реплаев, каждый сходит за пользователем.
Я бы хранил данные о пользователе в БД сервера и загружал вместе с реплаем.

2024-02-10 15:47 UTC, Olegas commented on packages/client/src/widgets/comment/Reply.tsx
> +    getUserById();
Аналогичная проблема в комментариях. Топик выводит комментарии, каждый из них лезет за пользователем.

2024-02-10 15:47 UTC, Olegas requested changes
Добрый день.
Написал несколько советов и одно критичное замечание.
Замечание надо переделать.
Написал подробно в комментариях к коду в чем проблема

2024-02-11 19:14 UTC, Olegas requested changes
Решили проблему запроса дублей но в целом стало не сильно лучше. Теперь у решения появилась дополнительная проблема - там где ты делаешь setUsersById возможна гонка и несколько завершившихся вместе запросов могу переписать данные друг друга (это будет происходить на 56 строке).
Мне кажется лучше тогда либо открутить аватарки вообще, либо сделать что бы они с сервера приходили а клиент за ними сам отдельно не ходил. 
Как вариант - сейчас сделать на клиенте что сервер будет присылать и пока форум будет без аватарок, и взять в спринт задачку что бы поддержать на бэке это.
Может вам с куратором команды еще посоветоваться как лучше сделать?

2024-02-11 21:40 UTC, shumilina-polina commented
> Как вариант - сейчас сделать на клиенте что сервер будет присылать и пока форум будет без аватарок, и взять в спринт задачку что бы поддержать на бэке это

Убрала запрос юзеров, вместо имени отображается id пользователя, аватарка генерируется исходя из него же. Взяли на доработку бэк и поправлю клиент

2024-02-12 05:28 UTC, Olegas approved these changes
Задача принята

2024-02-12 21:16 UTC, merged