COD-17: Добавлен axios. Логика авторизации и AuthGuard
kakbutos/MatchThree pull request #5
Opened 2023-12-11 04:01 UTC by belyshevaoksanai

### Какую задачу решаем

Добавление логики авторизации:
- добавлен axios
- запросы siginin/logout
- спиннер стилизованный под космо-тему
- AuthGuard

### Видяшка

https://github.com/kakbutos/MatchThree/assets/98637827/483d91ce-7559-4bda-b1ad-4a3bf7e58828

2023-12-11 08:40 UTC, shumilina-polina commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
сомневаюсь, что безопасно логировать через localstorage. Любой зайдет в devtools и изменит false на true

2023-12-11 11:19 UTC, belyshevaoksanai commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
К данным ведь всё равно доступа не будет так как запрос упадет с 401. Доступа к cookie у нас нет из JS чтобы определить залогинен или нет.
Можно запрос делать current и по нему определять валидный ли пользователь, но это тоже самое что если произойдет нужный запрос на странице и отвалится по причине того что не авторизован, оттуда редирект добавлю.

Или есть еще варианты?

2023-12-11 15:57 UTC, kakbutos commented
можешь скача obs studio для записи видео бесплатный) чтоб не использовать bandicam)))

2023-12-11 16:31 UTC, kakbutos commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
мы потом вроде в любом случае будем докручивать авторизацию через oAuth. Я кончено не работал с ней, но с jwt было дело. Возможно я конечно там с точки зрения безопасности не лучшим образом действовал, но суть в том, что с бэка будет возвращаться два токена, которые мы потом будем хранить и отправлять при запросах на бэк, а уже от этих токенов будет приходить ответ, есть ли доступ у пользователя
Ну, в общем, я к тому, что сейчас можно наверно пока забить на это, потом мы токены будем хранить в redux.А сйчас максимум там просто хранить не чистыми данными в локсалсторедж, а сделать какой то хэш и соль добавить, чтобы не было так очевидно что этот ключ значит

2023-12-11 16:31 UTC, kakbutos commented on packages/client/src/shared/components/spinner/spinner.module.scss
> +.loader_star {
блин у нас то snake_case, то camelCase в стилях)

2023-12-11 16:31 UTC, kakbutos commented on packages/client/src/utils/http-transport.ts
> +  static API_URL = 'https://ya-praktikum.tech/api/v2';
папка constants грустит сейчас))) вы же так ее защищали ахахха

2023-12-11 16:48 UTC, belyshevaoksanai commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
так это не ключ в localstorage) а только true/false к isLogged, ключ автоматически выставляется в cookie с HttpOnly; Secure. Доступа из JS  к нему нету, он сам добавляется ко всем запросам.

2023-12-11 16:49 UTC, belyshevaoksanai commented on packages/client/src/utils/http-transport.ts
> +  static API_URL = 'https://ya-praktikum.tech/api/v2';
ой всё)

2023-12-11 17:47 UTC, kakbutos approved these changes

2023-12-11 17:58 UTC, kakbutos commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
поговорили и решили оставить сейчас в localStorage, чтобы понимать авторизован ли пользователь

в дальнейшем будет при ините страницы уже получение токенов с помощью которых мы сможем понимать, авторизован ли пользователь на странице и выпилим этот ключ в localStorage

но возможно есть лучше решение в нынешних реалиях)

2023-12-12 07:11 UTC, Wintori requested changes

2023-12-12 07:11 UTC, Wintori commented on packages/client/src/utils/http-transport.ts
> +  protected endpoint = '';
тут можно просто написать `protected endpoint: string;`, а в конструкторе его инициализацию уже проводить, вроде всегда так делается

2023-12-12 07:46 UTC, belyshevaoksanai commented on packages/client/src/utils/http-transport.ts
> +  protected endpoint = '';
Ок, готово

2023-12-12 08:01 UTC, Wintori approved these changes
Огонь!

2023-12-12 15:47 UTC, DazzlingFame approved these changes
Привет! Отличная работа. Написал несколько комментариев в коде, но критичных среди них нет, работу принимаю.

2023-12-12 15:47 UTC, DazzlingFame commented on packages/client/src/pages/login/Login.tsx
> +  <ImageLayout urlBackgroundImage="/src/assets/images/racket.svg">
_Не критично к исправлению_

В крупных проектах обычно не принято указывать путь к картинке прямо в коде. Тут может быть 2 варианта исправления:
1. Импортировать svg как компонент
2. Вынести путь в отдельную константу и положить в отдельный файл с "ссылками" на картинки

2023-12-12 15:47 UTC, DazzlingFame commented on packages/client/src/pages/menu/Menu.tsx
> +// TODO COD-14 Временная заглушка для меню с кнопкой для выхода из аккаунта
Круто, что в комментариях сразу указываешь описание и задачу, где это будет исправлено! Это очень правильный подход

2023-12-12 15:47 UTC, DazzlingFame commented on packages/client/src/services/auth/auth.ts
> +    return localStorage.getItem(IS_LOGGED) === 'true';
Хранить факт авторизации в сторе, при том, что сам токен лежит в другом месте, неплохая мысль. В будущем, конечно, стоит перейти на понимание факта авторизации по наличию токена в redux

2023-12-12 15:47 UTC, DazzlingFame commented on packages/client/src/widgets/auth-form/AuthForm.tsx
> +export const AuthForm = () => {
_Не критично к исправлению_

Желательно все компоненты типизировать через `React.FC`, это помогает защититься от случайных ошибок

2023-12-13 05:45 UTC, merged